# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 15:15
from __future__ import unicode_literals

from django.db import migrations, models


def write_has_children(apps, schema_editor):
    Comment = apps.get_model("blog", "Comment")
    db_alias = schema_editor.connection.alias
    for comment in Comment.objects.using(db_alias).filter(parent_comment__isnull=False):
        comment.parent_comment.has_children = True
        comment.parent_comment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='has_children',
            field=models.BooleanField(default=False, verbose_name='есть ли ответы на комментарий'),
        ),
        migrations.RunPython(write_has_children)
    ]
