# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170328_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='level',
            field=models.IntegerField(default=1, verbose_name='уровень вложенности'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='max_unfold_comment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='thread_comments', to='blog.Comment', verbose_name='последний полгружаемый по умолчанию комментарий в треде'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.Comment', verbose_name='начальный комментарий'),
        ),
    ]
