# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170329_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='level',
            field=models.IntegerField(blank=True, null=True, verbose_name='уровень вложенности'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='max_unfold_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_comments', to='blog.Comment', verbose_name='последний полгружаемый по умолчанию комментарий в треде'),
        ),
    ]
