# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import tastypie.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170329_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='text',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='text',
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default='', verbose_name='текст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=tastypie.utils.timezone.now, verbose_name='время создания'),
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default='', verbose_name='текст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=tastypie.utils.timezone.now, verbose_name='время создания'),
        ),
    ]
